import {
  addDaysToDate,
  formatIcsDateTimeLocal
} from "@/lib/export/ics";
import type { ExportDistanceDay, ExportTrip, ExportWeatherDay } from "@/lib/export/trip-export-adapter";
import { formatInterestLabel, formatMoney, formatPaceLabel } from "@/lib/utils";
import {
  costBadgeLabel,
  formatApproxMoney,
  formatMoney as formatBudgetMoney,
  getCostAmount
} from "@/lib/budget/format";
import type { ItineraryItem } from "@/types/trip";

export type TripPdfLineVariant =
  | "title"
  | "subtitle"
  | "heading"
  | "subheading"
  | "body"
  | "muted"
  | "small"
  | "footer";

export type TripPdfLine = {
  text: string;
  variant?: TripPdfLineVariant;
  indent?: number;
};

export function buildTripPdfLines(exportTrip: ExportTrip): TripPdfLine[] {
  const lines: TripPdfLine[] = [
    { text: exportTrip.destination || "Trip itinerary", variant: "title" },
    { text: formatTripSubtitle(exportTrip), variant: "subtitle" }
  ];

  const summaryLine = buildTripFacts(exportTrip).join(" · ");
  if (summaryLine) {
    lines.push({ text: summaryLine, variant: "body" });
  }

  if (exportTrip.interests?.length) {
    lines.push({
      text: `Interests: ${exportTrip.interests.map(formatInterestLabel).join(", ")}`,
      variant: "muted"
    });
  }

  if (exportTrip.itinerary?.summary) {
    lines.push({ text: "Overview", variant: "heading" });
    lines.push({ text: exportTrip.itinerary.summary, variant: "body" });
  }

  appendAccommodationSummary(lines, exportTrip);

  if (exportTrip.itinerary?.days?.length) {
    lines.push({ text: "Day-by-day itinerary", variant: "heading" });

    exportTrip.itinerary.days.forEach((day, dayIndex) => {
      const dayNumber = day.day || dayIndex + 1;
      lines.push({
        text: `Day ${dayNumber}${formatDayDate(exportTrip.startDate, dayNumber)}${day.title ? ` - ${day.title}` : ""}`,
        variant: "subheading"
      });

      if (!day.items?.length) {
        lines.push({ text: "No itinerary items listed.", variant: "muted", indent: 14 });
        return;
      }

      day.items.forEach((item) => {
        lines.push({ text: formatItemHeading(item), variant: "body", indent: 14 });
        if (item.note) {
          lines.push({ text: item.note, variant: "muted", indent: 28 });
        }
        if (item.place) {
          lines.push({
            text: [item.place.name, item.place.address].filter(Boolean).join(" - "),
            variant: "small",
            indent: 28
          });
          if (item.place.mapUrl) {
            lines.push({ text: `Map: ${item.place.mapUrl}`, variant: "small", indent: 28 });
          }
        }
        const costBadge = costBadgeLabel(item.estimatedCost, exportTrip.budgetCurrency ?? undefined);
        if (costBadge) {
          lines.push({
            text: `Estimated cost: ${costBadge}`,
            variant: "small",
            indent: 28
          });
        }
      });
    });
  }

  appendBudgetSummary(lines, exportTrip);
  appendWeatherSummary(lines, exportTrip.weatherSummary);
  appendDistanceSummary(lines, exportTrip.distanceSummary);

  lines.push({
    text: `Generated by AI Travel Planner on ${new Intl.DateTimeFormat("en", {
      dateStyle: "medium"
    }).format(new Date())}`,
    variant: "footer"
  });

  return lines;
}

function buildTripFacts(exportTrip: ExportTrip): string[] {
  return [
    `${exportTrip.days} ${exportTrip.days === 1 ? "day" : "days"}`,
    exportTrip.travelers
      ? `${exportTrip.travelers} ${exportTrip.travelers === 1 ? "traveler" : "travelers"}`
      : null,
    exportTrip.budgetAmount != null
      ? `Budget ${formatMoney(exportTrip.budgetAmount, exportTrip.budgetCurrency ?? undefined)}`
      : null,
    exportTrip.pace ? `${formatPaceLabel(exportTrip.pace)} pace` : null
  ].filter((value): value is string => Boolean(value));
}

function formatTripSubtitle(exportTrip: ExportTrip): string {
  if (!exportTrip.startDate) {
    return "Itinerary summary";
  }

  const endDate = addDaysToDate(exportTrip.startDate, Math.max(exportTrip.days - 1, 0));
  if (Number.isNaN(endDate.getTime()) || exportTrip.days <= 1) {
    return formatReadableDate(exportTrip.startDate);
  }

  return `${formatReadableDate(exportTrip.startDate)} - ${formatReadableDateFromDate(endDate)}`;
}

function formatDayDate(startDate: string | null | undefined, dayNumber: number): string {
  if (!startDate) {
    return "";
  }

  const date = addDaysToDate(startDate, dayNumber - 1);
  if (Number.isNaN(date.getTime())) {
    return "";
  }

  return ` · ${formatReadableDateFromDate(date)}`;
}

function formatItemHeading(item: ItineraryItem): string {
  const parts = [
    item.time || "Untimed",
    item.name || "Itinerary item",
    item.type ? formatInterestLabel(item.type) : null
  ].filter(Boolean);

  return parts.join(" - ");
}

function appendAccommodationSummary(lines: TripPdfLine[], exportTrip: ExportTrip) {
  const accommodation = exportTrip.accommodation;
  if (exportTrip.source !== "private" || !accommodation) {
    return;
  }

  lines.push({ text: "Accommodation", variant: "heading" });
  lines.push({
    text: [accommodation.name, formatInterestLabel(accommodation.type)]
      .filter(Boolean)
      .join(" - "),
    variant: "body",
    indent: 14
  });
  if (accommodation.address) {
    lines.push({ text: accommodation.address, variant: "small", indent: 28 });
  }
  if (accommodation.checkInDate || accommodation.checkOutDate) {
    lines.push({
      text: `Dates: ${[accommodation.checkInDate, accommodation.checkOutDate]
        .filter(Boolean)
        .join(" to ")}`,
      variant: "small",
      indent: 28
    });
  }
  const costBadge = costBadgeLabel(
    accommodation.estimatedCost,
    exportTrip.budgetCurrency ?? undefined
  );
  if (costBadge) {
    lines.push({ text: `Estimated stay cost: ${costBadge}`, variant: "small", indent: 28 });
  }
  if (accommodation.notes) {
    lines.push({ text: accommodation.notes, variant: "muted", indent: 28 });
  }
}

// appendBudgetSummary adds a private-only budget rollup. The public export never
// includes the private trip budget; item-level cost badges still render inline.
function appendBudgetSummary(lines: TripPdfLine[], exportTrip: ExportTrip) {
  if (exportTrip.source !== "private") {
    return;
  }
  if (exportTrip.budgetSummary) {
    const summary = exportTrip.budgetSummary;
    const currency = summary.currency ?? exportTrip.budgetCurrency ?? undefined;
    lines.push({ text: "Budget summary", variant: "heading" });
    if (summary.tripBudget != null) {
      lines.push({
        text: `Trip budget: ${formatBudgetMoney(summary.tripBudget, currency)}`,
        variant: "body",
        indent: 14
      });
      if ((summary.overBudgetBy ?? 0) > 0) {
        lines.push({
          text: `Over budget by: ${formatApproxMoney(summary.overBudgetBy, currency)}`,
          variant: "body",
          indent: 14
        });
      } else if (summary.remaining != null) {
        lines.push({
          text: `Remaining: ${formatApproxMoney(summary.remaining, currency)}`,
          variant: "body",
          indent: 14
        });
      }
    }
    lines.push({
      text: `Estimated total: ${formatApproxMoney(summary.estimatedTotal, currency)}`,
      variant: "body",
      indent: 14
    });
    if (summary.accommodationTotal != null) {
      lines.push({
        text: `Accommodation: ${formatApproxMoney(summary.accommodationTotal, currency)}`,
        variant: "small",
        indent: 28
      });
    }
    if (summary.originalCurrencyTotals?.length) {
      lines.push({ text: "Original currency totals:", variant: "small", indent: 28 });
      summary.originalCurrencyTotals.forEach((total) => {
        lines.push({
          text: `${total.currency}: ${formatBudgetMoney(total.amount, total.currency)}`,
          variant: "small",
          indent: 42
        });
      });
    }
    if (summary.conversionWarnings?.length) {
      lines.push({
        text: "Some costs could not be converted and are not included in the total.",
        variant: "small",
        indent: 28
      });
    }
    if (summary.exchangeRateInfo) {
      lines.push({
        text: "Approximate conversions; no historical rates or financial advice.",
        variant: "small",
        indent: 28
      });
    }
    return;
  }
  const days = exportTrip.itinerary?.days ?? [];
  const currency = exportTrip.budgetCurrency ?? undefined;
  let estimatedTotal = 0;
  let costedItems = 0;
  const dayTotals: { dayNumber: number; total: number }[] = [];
  const accommodationCost = getCostAmount(exportTrip.accommodation?.estimatedCost);
  if (accommodationCost != null) {
    estimatedTotal += accommodationCost;
    costedItems += 1;
  }
  if (days.length === 0 && accommodationCost == null && exportTrip.budgetAmount == null) {
    return;
  }

  days.forEach((day, dayIndex) => {
    let dayTotal = 0;
    (day.items ?? []).forEach((item) => {
      const amount = getCostAmount(item.estimatedCost);
      if (amount != null) {
        dayTotal += amount;
        estimatedTotal += amount;
        costedItems += 1;
      }
    });
    dayTotals.push({ dayNumber: day.day || dayIndex + 1, total: dayTotal });
  });

  if (costedItems === 0 && exportTrip.budgetAmount == null) {
    return;
  }

  lines.push({ text: "Budget summary", variant: "heading" });
  if (exportTrip.budgetAmount != null) {
    lines.push({
      text: `Trip budget: ${formatMoney(exportTrip.budgetAmount, currency)}`,
      variant: "body",
      indent: 14
    });
    const remaining = exportTrip.budgetAmount - estimatedTotal;
    lines.push({
      text:
        remaining >= 0
          ? `Remaining: ${formatMoney(remaining, currency)}`
          : `Over budget by: ${formatMoney(Math.abs(remaining), currency)}`,
      variant: "body",
      indent: 14
    });
  }
  lines.push({
    text: `Estimated total: ${formatMoney(estimatedTotal, currency)}`,
    variant: "body",
    indent: 14
  });
  if (accommodationCost != null) {
    lines.push({
      text: `Accommodation: ${formatMoney(accommodationCost, currency)}`,
      variant: "small",
      indent: 28
    });
  }
  dayTotals
    .filter((entry) => entry.total > 0)
    .forEach((entry) => {
      lines.push({
        text: `Day ${entry.dayNumber}: ${formatMoney(entry.total, currency)}`,
        variant: "small",
        indent: 28
      });
    });
}

function appendWeatherSummary(lines: TripPdfLine[], weatherSummary?: ExportWeatherDay[] | null) {
  if (!weatherSummary?.length) {
    return;
  }

  lines.push({ text: "Weather summary", variant: "heading" });
  weatherSummary.forEach((day) => {
    const temps =
      day.temperatureMinC != null && day.temperatureMaxC != null
        ? `${formatNumber(day.temperatureMinC)}-${formatNumber(day.temperatureMaxC)} C`
        : null;
    const rain =
      day.precipitationChance != null ? `${formatNumber(day.precipitationChance)}% rain` : null;

    lines.push({
      text: [
        `Day ${day.dayNumber}`,
        day.date ? formatReadableDate(day.date) : null,
        day.summary,
        temps,
        rain
      ]
        .filter(Boolean)
        .join(" - "),
      variant: "body",
      indent: 14
    });
  });
}

function appendDistanceSummary(lines: TripPdfLine[], distanceSummary?: ExportDistanceDay[] | null) {
  if (!distanceSummary?.length) {
    return;
  }

  lines.push({ text: "Distance summary", variant: "heading" });
  distanceSummary.forEach((day) => {
    lines.push({
      text: [
        `Day ${day.dayNumber}`,
        day.distanceKm != null ? `${day.distanceKm.toFixed(1)} km` : null,
        day.walkingMinutes != null ? `${Math.round(day.walkingMinutes)} min walking` : null
      ]
        .filter(Boolean)
        .join(" - "),
      variant: "body",
      indent: 14
    });
  });
}

function formatReadableDate(value: string): string {
  const date = addDaysToDate(value, 0);
  return Number.isNaN(date.getTime()) ? value : formatReadableDateFromDate(date);
}

function formatReadableDateFromDate(date: Date): string {
  const value = formatIcsDateTimeLocal(date, 0, 0).slice(0, 8);
  const normalized = `${value.slice(0, 4)}-${value.slice(4, 6)}-${value.slice(6, 8)}T00:00:00Z`;
  return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeZone: "UTC" }).format(
    new Date(normalized)
  );
}

function formatNumber(value: number): string {
  return Number.isInteger(value) ? String(value) : value.toFixed(1);
}
