import {
  addDaysToDate,
  formatIcsDateTimeLocal
} from "@/lib/export/ics";
import type { ExportDistanceDay, ExportTrip, ExportWeatherDay } from "@/lib/export/trip-export-adapter";
import { formatInterestLabel, formatMoney, formatPaceLabel } from "@/lib/utils";
import {
  costBadgeLabel,
  formatApproxMoney,
  formatMoney as formatBudgetMoney,
  getCostAmount
} from "@/entities/budget/model";
import type { ItineraryItem } from "@/entities/trip/model";

export type TripPdfLineVariant =
  | "title"
  | "subtitle"
  | "heading"
  | "subheading"
  | "body"
  | "muted"
  | "small"
  | "footer";

export type TripPdfLine = {
  text: string;
  variant?: TripPdfLineVariant;
  indent?: number;
};

export function buildTripPdfLines(exportTrip: ExportTrip): TripPdfLine[] {
  const lines: TripPdfLine[] = [
    { text: exportTrip.destination || "Trip itinerary", variant: "title" },
    { text: formatTripSubtitle(exportTrip), variant: "subtitle" }
  ];

  const summaryLine = buildTripFacts(exportTrip).join(" · ");
  if (summaryLine) {
    lines.push({ text: summaryLine, variant: "body" });
  }

  if (exportTrip.interests?.length) {
    lines.push({
      text: `Interests: ${exportTrip.interests.map(formatInterestLabel).join(", ")}`,
      variant: "muted"
    });
  }

  if (exportTrip.itinerary?.summary) {
    lines.push({ text: "Overview", variant: "heading" });
    lines.push({ text: exportTrip.itinerary.summary, variant: "body" });
  }

  appendRouteSummary(lines, exportTrip);
  appendAccommodationSummary(lines, exportTrip);

  if (exportTrip.itinerary?.days?.length) {
    lines.push({ text: "Day-by-day itinerary", variant: "heading" });

    exportTrip.itinerary.days.forEach((day, dayIndex) => {
      const dayNumber = day.day || dayIndex + 1;
      lines.push({
        text: `Day ${dayNumber}${formatDayDate(exportTrip.startDate, dayNumber)}${day.title ? ` - ${day.title}` : ""}`,
        variant: "subheading"
      });

      if (!day.items?.length) {
        lines.push({ text: "No itinerary items listed.", variant: "muted", indent: 14 });
        return;
      }

      day.items.forEach((item) => {
        lines.push({ text: formatItemHeading(item), variant: "body", indent: 14 });
        if (item.note) {
          lines.push({ text: item.note, variant: "muted", indent: 28 });
        }
        if (item.description && item.description !== item.note) {
          lines.push({ text: item.description, variant: "muted", indent: 28 });
        }
        if (item.transfer) {
          lines.push({
            text: `${item.transfer.from} -> ${item.transfer.to} by ${formatRouteToken(item.transfer.mode)}`,
            variant: "small",
            indent: 28
          });
          const transferDetails = [
            item.transfer.estimatedDurationMinutes != null
              ? `~${item.transfer.estimatedDurationMinutes} min`
              : null,
            item.transfer.estimatedDistanceKm != null
              ? `${item.transfer.estimatedDistanceKm.toFixed(1)} km`
              : null,
            "Verify schedules before travel"
          ].filter(Boolean);
          lines.push({ text: transferDetails.join(" · "), variant: "small", indent: 28 });
          if (item.transfer.warnings?.length) {
            lines.push({ text: item.transfer.warnings.join("; "), variant: "small", indent: 28 });
          }
        }
        if (item.place) {
          lines.push({
            text: [item.place.name, item.place.address].filter(Boolean).join(" - "),
            variant: "small",
            indent: 28
          });
          if (item.place.mapUrl) {
            lines.push({ text: `Map: ${item.place.mapUrl}`, variant: "small", indent: 28 });
          }
        }
        const costBadge = costBadgeLabel(item.estimatedCost, exportTrip.budgetCurrency ?? undefined);
        if (costBadge) {
          lines.push({
            text: `Estimated cost: ${costBadge}`,
            variant: "small",
            indent: 28
          });
        }
      });
    });
  }

  appendBudgetSummary(lines, exportTrip);
  appendChecklistSummary(lines, exportTrip);
  appendReminderSummary(lines, exportTrip);
  appendWeatherSummary(lines, exportTrip.weatherSummary);
  appendDistanceSummary(lines, exportTrip.distanceSummary);

  lines.push({
    text: `Generated by AI Travel Planner on ${new Intl.DateTimeFormat("en", {
      dateStyle: "medium"
    }).format(new Date())}`,
    variant: "footer"
  });

  return lines;
}

function appendRouteSummary(lines: TripPdfLine[], exportTrip: ExportTrip) {
  const route = exportTrip.route;
  if (!route?.stops?.length) {
    return;
  }

  lines.push({ text: "Route overview", variant: "heading" });
  const sequence = [
    route.origin?.name,
    ...route.stops.map((stop) => stop.destination || stop.city).filter(Boolean)
  ].filter(Boolean);
  if (sequence.length) {
    lines.push({ text: sequence.join(" -> "), variant: "body", indent: 14 });
  }
  route.stops.forEach((stop, index) => {
    const dates = [stop.arrivalDate, stop.departureDate].filter(Boolean).join(" to ");
    const details = [
      `${index + 1}. ${stop.destination || stop.city || "Stop"}`,
      stop.country,
      stop.nights != null ? `${stop.nights} night${stop.nights === 1 ? "" : "s"}` : null,
      dates || null,
      stop.accommodationHint ? formatRouteToken(stop.accommodationHint) : null
    ].filter(Boolean);
    lines.push({ text: details.join(" · "), variant: "small", indent: 28 });
  });
  route.legs?.forEach((leg) => {
    const costBadge = costBadgeLabel(leg.estimatedCost, exportTrip.budgetCurrency ?? undefined);
    const details = [
      `${leg.fromName || leg.fromStopId} -> ${leg.toName || leg.toStopId}`,
      formatRouteToken(leg.mode),
      leg.estimatedDurationMinutes != null ? `~${leg.estimatedDurationMinutes} min` : null,
      leg.estimatedDistanceKm != null ? `${leg.estimatedDistanceKm.toFixed(1)} km` : null,
      costBadge ? `est. ${costBadge}` : null
    ].filter(Boolean);
    lines.push({ text: details.join(" · "), variant: "small", indent: 28 });
  });
  lines.push({
    text: "Transfer durations and costs are planning estimates; verify schedules before travel.",
    variant: "muted",
    indent: 14
  });
}

function buildTripFacts(exportTrip: ExportTrip): string[] {
  return [
    `${exportTrip.days} ${exportTrip.days === 1 ? "day" : "days"}`,
    exportTrip.travelers
      ? `${exportTrip.travelers} ${exportTrip.travelers === 1 ? "traveler" : "travelers"}`
      : null,
    exportTrip.budgetAmount != null
      ? `Budget ${formatMoney(exportTrip.budgetAmount, exportTrip.budgetCurrency ?? undefined)}`
      : null,
    exportTrip.pace ? `${formatPaceLabel(exportTrip.pace)} pace` : null
  ].filter((value): value is string => Boolean(value));
}

function formatTripSubtitle(exportTrip: ExportTrip): string {
  if (!exportTrip.startDate) {
    return "Itinerary summary";
  }

  const endDate = addDaysToDate(exportTrip.startDate, Math.max(exportTrip.days - 1, 0));
  if (Number.isNaN(endDate.getTime()) || exportTrip.days <= 1) {
    return formatReadableDate(exportTrip.startDate);
  }

  return `${formatReadableDate(exportTrip.startDate)} - ${formatReadableDateFromDate(endDate)}`;
}

function formatDayDate(startDate: string | null | undefined, dayNumber: number): string {
  if (!startDate) {
    return "";
  }

  const date = addDaysToDate(startDate, dayNumber - 1);
  if (Number.isNaN(date.getTime())) {
    return "";
  }

  return ` · ${formatReadableDateFromDate(date)}`;
}

function formatItemHeading(item: ItineraryItem): string {
  if (item.transfer) {
    return [
      item.time || "Untimed",
      `Transfer: ${item.transfer.from} -> ${item.transfer.to}`,
      formatRouteToken(item.transfer.mode)
    ]
      .filter(Boolean)
      .join(" - ");
  }
  const parts = [
    item.time || "Untimed",
    item.name || "Itinerary item",
    item.type ? formatInterestLabel(item.type) : null
  ].filter(Boolean);

  return parts.join(" - ");
}

function formatRouteToken(value: string | null | undefined): string {
  if (!value) {
    return "";
  }
  return String(value)
    .replace(/_/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function appendAccommodationSummary(lines: TripPdfLine[], exportTrip: ExportTrip) {
  const accommodation = exportTrip.accommodation;
  if (exportTrip.source !== "private" || !accommodation) {
    return;
  }

  lines.push({ text: "Accommodation", variant: "heading" });
  lines.push({
    text: [accommodation.name, formatInterestLabel(accommodation.type)]
      .filter(Boolean)
      .join(" - "),
    variant: "body",
    indent: 14
  });
  if (accommodation.address) {
    lines.push({ text: accommodation.address, variant: "small", indent: 28 });
  }
  if (accommodation.checkInDate || accommodation.checkOutDate) {
    lines.push({
      text: `Dates: ${[accommodation.checkInDate, accommodation.checkOutDate]
        .filter(Boolean)
        .join(" to ")}`,
      variant: "small",
      indent: 28
    });
  }
  const costBadge = costBadgeLabel(
    accommodation.estimatedCost,
    exportTrip.budgetCurrency ?? undefined
  );
  if (costBadge) {
    lines.push({ text: `Estimated stay cost: ${costBadge}`, variant: "small", indent: 28 });
  }
  if (accommodation.notes) {
    lines.push({ text: accommodation.notes, variant: "muted", indent: 28 });
  }
}

function appendChecklistSummary(lines: TripPdfLine[], exportTrip: ExportTrip) {
  if (exportTrip.source !== "private" || !exportTrip.checklist?.items?.length) {
    return;
  }

  const items = exportTrip.checklist.items;
  const checked = items.filter((item) => item.checked).length;
  lines.push({ text: exportTrip.checklist.title || "Packing checklist", variant: "heading" });
  lines.push({
    text: `${checked}/${items.length} complete`,
    variant: "body",
    indent: 14
  });
  if (exportTrip.checklist.summary) {
    lines.push({ text: exportTrip.checklist.summary, variant: "muted", indent: 14 });
  }

  items.forEach((item) => {
    const assignee = item.assignedToDisplayName || item.assignedToUserId;
    const details = [
      item.priority ? formatRouteToken(item.priority) : null,
      item.category ? formatRouteToken(item.category) : null,
      item.dueDate ? `Due ${formatReadableDate(item.dueDate)}` : null,
      assignee ? `Assigned to ${assignee}` : null
    ].filter(Boolean);
    lines.push({
      text: `${item.checked ? "[x]" : "[ ]"} ${item.quantity ? `${item.quantity}x ` : ""}${item.title}`,
      variant: "body",
      indent: 14
    });
    if (details.length) {
      lines.push({ text: details.join(" - "), variant: "small", indent: 28 });
    }
    if (item.description) {
      lines.push({ text: item.description, variant: "muted", indent: 28 });
    }
  });
}

function appendReminderSummary(lines: TripPdfLine[], exportTrip: ExportTrip) {
  if (exportTrip.source !== "private" || !exportTrip.reminders?.length) {
    return;
  }

  const reminders = exportTrip.reminders.filter(
    (reminder) => reminder.status !== "cancelled" && reminder.status !== "disabled"
  );
  if (!reminders.length) {
    return;
  }

  lines.push({ text: "Pre-trip reminders", variant: "heading" });
  reminders.forEach((reminder) => {
    const assignee = reminder.assignedToDisplayName || reminder.assignedToUserId;
    const details = [
      formatRouteToken(reminder.priority),
      formatRouteToken(reminder.category),
      formatRouteToken(reminder.status),
      assignee ? `Assigned to ${assignee}` : null
    ].filter(Boolean);
    lines.push({
      text: `${formatReadableDate(reminder.triggerDate)}${reminder.triggerTime ? ` ${reminder.triggerTime}` : ""} - ${reminder.title}`,
      variant: "body",
      indent: 14
    });
    if (details.length) {
      lines.push({ text: details.join(" - "), variant: "small", indent: 28 });
    }
    if (reminder.description) {
      lines.push({ text: reminder.description, variant: "muted", indent: 28 });
    }
  });
  lines.push({
    text: "Reminders are preparation aids. Verify official requirements yourself.",
    variant: "muted",
    indent: 14
  });
}

// appendBudgetSummary adds a private-only budget rollup. The public export never
// includes the private trip budget; item-level cost badges still render inline.
function appendBudgetSummary(lines: TripPdfLine[], exportTrip: ExportTrip) {
  if (exportTrip.source !== "private") {
    return;
  }
  if (exportTrip.budgetSummary) {
    const summary = exportTrip.budgetSummary;
    const currency = summary.currency ?? exportTrip.budgetCurrency ?? undefined;
    lines.push({ text: "Budget summary", variant: "heading" });
    if (summary.tripBudget != null) {
      lines.push({
        text: `Trip budget: ${formatBudgetMoney(summary.tripBudget, currency)}`,
        variant: "body",
        indent: 14
      });
      if ((summary.overBudgetBy ?? 0) > 0) {
        lines.push({
          text: `Over budget by: ${formatApproxMoney(summary.overBudgetBy, currency)}`,
          variant: "body",
          indent: 14
        });
      } else if (summary.remaining != null) {
        lines.push({
          text: `Remaining: ${formatApproxMoney(summary.remaining, currency)}`,
          variant: "body",
          indent: 14
        });
      }
    }
    lines.push({
      text: `Estimated total: ${formatApproxMoney(summary.estimatedTotal, currency)}`,
      variant: "body",
      indent: 14
    });
    if (summary.accommodationTotal != null) {
      lines.push({
        text: `Accommodation: ${formatApproxMoney(summary.accommodationTotal, currency)}`,
        variant: "small",
        indent: 28
      });
    }
    if (summary.originalCurrencyTotals?.length) {
      lines.push({ text: "Original currency totals:", variant: "small", indent: 28 });
      summary.originalCurrencyTotals.forEach((total) => {
        lines.push({
          text: `${total.currency}: ${formatBudgetMoney(total.amount, total.currency)}`,
          variant: "small",
          indent: 42
        });
      });
    }
    if (summary.conversionWarnings?.length) {
      lines.push({
        text: "Some costs could not be converted and are not included in the total.",
        variant: "small",
        indent: 28
      });
    }
    if (summary.exchangeRateInfo) {
      lines.push({
        text: "Approximate conversions; no historical rates or financial advice.",
        variant: "small",
        indent: 28
      });
    }
    return;
  }
  const days = exportTrip.itinerary?.days ?? [];
  const currency = exportTrip.budgetCurrency ?? undefined;
  let estimatedTotal = 0;
  let costedItems = 0;
  const dayTotals: { dayNumber: number; total: number }[] = [];
  const accommodationCost = getCostAmount(exportTrip.accommodation?.estimatedCost);
  if (accommodationCost != null) {
    estimatedTotal += accommodationCost;
    costedItems += 1;
  }
  if (days.length === 0 && accommodationCost == null && exportTrip.budgetAmount == null) {
    return;
  }

  days.forEach((day, dayIndex) => {
    let dayTotal = 0;
    (day.items ?? []).forEach((item) => {
      const amount = getCostAmount(item.estimatedCost);
      if (amount != null) {
        dayTotal += amount;
        estimatedTotal += amount;
        costedItems += 1;
      }
    });
    dayTotals.push({ dayNumber: day.day || dayIndex + 1, total: dayTotal });
  });

  if (costedItems === 0 && exportTrip.budgetAmount == null) {
    return;
  }

  lines.push({ text: "Budget summary", variant: "heading" });
  if (exportTrip.budgetAmount != null) {
    lines.push({
      text: `Trip budget: ${formatMoney(exportTrip.budgetAmount, currency)}`,
      variant: "body",
      indent: 14
    });
    const remaining = exportTrip.budgetAmount - estimatedTotal;
    lines.push({
      text:
        remaining >= 0
          ? `Remaining: ${formatMoney(remaining, currency)}`
          : `Over budget by: ${formatMoney(Math.abs(remaining), currency)}`,
      variant: "body",
      indent: 14
    });
  }
  lines.push({
    text: `Estimated total: ${formatMoney(estimatedTotal, currency)}`,
    variant: "body",
    indent: 14
  });
  if (accommodationCost != null) {
    lines.push({
      text: `Accommodation: ${formatMoney(accommodationCost, currency)}`,
      variant: "small",
      indent: 28
    });
  }
  dayTotals
    .filter((entry) => entry.total > 0)
    .forEach((entry) => {
      lines.push({
        text: `Day ${entry.dayNumber}: ${formatMoney(entry.total, currency)}`,
        variant: "small",
        indent: 28
      });
    });
}

function appendWeatherSummary(lines: TripPdfLine[], weatherSummary?: ExportWeatherDay[] | null) {
  if (!weatherSummary?.length) {
    return;
  }

  lines.push({ text: "Weather summary", variant: "heading" });
  weatherSummary.forEach((day) => {
    const temps =
      day.temperatureMinC != null && day.temperatureMaxC != null
        ? `${formatNumber(day.temperatureMinC)}-${formatNumber(day.temperatureMaxC)} C`
        : null;
    const rain =
      day.precipitationChance != null ? `${formatNumber(day.precipitationChance)}% rain` : null;

    lines.push({
      text: [
        `Day ${day.dayNumber}`,
        day.date ? formatReadableDate(day.date) : null,
        day.summary,
        temps,
        rain
      ]
        .filter(Boolean)
        .join(" - "),
      variant: "body",
      indent: 14
    });
  });
}

function appendDistanceSummary(lines: TripPdfLine[], distanceSummary?: ExportDistanceDay[] | null) {
  if (!distanceSummary?.length) {
    return;
  }

  lines.push({ text: "Distance summary", variant: "heading" });
  distanceSummary.forEach((day) => {
    lines.push({
      text: [
        `Day ${day.dayNumber}`,
        day.distanceKm != null ? `${day.distanceKm.toFixed(1)} km` : null,
        day.walkingMinutes != null ? `${Math.round(day.walkingMinutes)} min walking` : null
      ]
        .filter(Boolean)
        .join(" - "),
      variant: "body",
      indent: 14
    });
  });
}

function formatReadableDate(value: string): string {
  const date = addDaysToDate(value, 0);
  return Number.isNaN(date.getTime()) ? value : formatReadableDateFromDate(date);
}

function formatReadableDateFromDate(date: Date): string {
  const value = formatIcsDateTimeLocal(date, 0, 0).slice(0, 8);
  const normalized = `${value.slice(0, 4)}-${value.slice(4, 6)}-${value.slice(6, 8)}T00:00:00Z`;
  return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeZone: "UTC" }).format(
    new Date(normalized)
  );
}

function formatNumber(value: number): string {
  return Number.isInteger(value) ? String(value) : value.toFixed(1);
}
