global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: trip-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - trip-service:8080

  - job_name: worker-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - worker-service:8090

  - job_name: external-integrations-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - external-integrations-service:8084

  - job_name: notification-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - notification-service:8086

  - job_name: auth-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - auth-service:8082

  - job_name: user-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - user-service:8083

  - job_name: ai-planning-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - ai-planning-service:8000

  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets:
          - rabbitmq:15692
