import {
  addDaysToDate,
  formatIcsDateTimeLocal
} from "@/lib/export/ics";
import type { ExportDistanceDay, ExportTrip, ExportWeatherDay } from "@/lib/export/trip-export-adapter";
import { formatInterestLabel, formatMoney, formatPaceLabel } from "@/lib/utils";
import type { ItineraryItem } from "@/types/trip";

export type TripPdfLineVariant =
  | "title"
  | "subtitle"
  | "heading"
  | "subheading"
  | "body"
  | "muted"
  | "small"
  | "footer";

export type TripPdfLine = {
  text: string;
  variant?: TripPdfLineVariant;
  indent?: number;
};

export function buildTripPdfLines(exportTrip: ExportTrip): TripPdfLine[] {
  const lines: TripPdfLine[] = [
    { text: exportTrip.destination || "Trip itinerary", variant: "title" },
    { text: formatTripSubtitle(exportTrip), variant: "subtitle" }
  ];

  const summaryLine = buildTripFacts(exportTrip).join(" · ");
  if (summaryLine) {
    lines.push({ text: summaryLine, variant: "body" });
  }

  if (exportTrip.interests?.length) {
    lines.push({
      text: `Interests: ${exportTrip.interests.map(formatInterestLabel).join(", ")}`,
      variant: "muted"
    });
  }

  if (exportTrip.itinerary?.summary) {
    lines.push({ text: "Overview", variant: "heading" });
    lines.push({ text: exportTrip.itinerary.summary, variant: "body" });
  }

  if (exportTrip.itinerary?.days?.length) {
    lines.push({ text: "Day-by-day itinerary", variant: "heading" });

    exportTrip.itinerary.days.forEach((day, dayIndex) => {
      const dayNumber = day.day || dayIndex + 1;
      lines.push({
        text: `Day ${dayNumber}${formatDayDate(exportTrip.startDate, dayNumber)}${day.title ? ` - ${day.title}` : ""}`,
        variant: "subheading"
      });

      if (!day.items?.length) {
        lines.push({ text: "No itinerary items listed.", variant: "muted", indent: 14 });
        return;
      }

      day.items.forEach((item) => {
        lines.push({ text: formatItemHeading(item), variant: "body", indent: 14 });
        if (item.note) {
          lines.push({ text: item.note, variant: "muted", indent: 28 });
        }
        if (item.place) {
          lines.push({
            text: [item.place.name, item.place.address].filter(Boolean).join(" - "),
            variant: "small",
            indent: 28
          });
          if (item.place.mapUrl) {
            lines.push({ text: `Map: ${item.place.mapUrl}`, variant: "small", indent: 28 });
          }
        }
        if (item.estimatedCost != null) {
          lines.push({
            text: `Estimated cost: ${formatMoney(item.estimatedCost, exportTrip.budgetCurrency ?? undefined)}`,
            variant: "small",
            indent: 28
          });
        }
      });
    });
  }

  appendWeatherSummary(lines, exportTrip.weatherSummary);
  appendDistanceSummary(lines, exportTrip.distanceSummary);

  lines.push({
    text: `Generated by AI Travel Planner on ${new Intl.DateTimeFormat("en", {
      dateStyle: "medium"
    }).format(new Date())}`,
    variant: "footer"
  });

  return lines;
}

export function TripPdfDocument({ exportTrip }: { exportTrip: ExportTrip }) {
  return (
    <article>
      {buildTripPdfLines(exportTrip).map((line, index) => {
        const Tag = line.variant === "title" ? "h1" : line.variant === "heading" ? "h2" : "p";
        return (
          <Tag key={`${line.variant ?? "body"}-${index}`} style={{ marginLeft: line.indent ?? 0 }}>
            {line.text}
          </Tag>
        );
      })}
    </article>
  );
}

function buildTripFacts(exportTrip: ExportTrip): string[] {
  return [
    `${exportTrip.days} ${exportTrip.days === 1 ? "day" : "days"}`,
    exportTrip.travelers
      ? `${exportTrip.travelers} ${exportTrip.travelers === 1 ? "traveler" : "travelers"}`
      : null,
    exportTrip.budgetAmount != null
      ? `Budget ${formatMoney(exportTrip.budgetAmount, exportTrip.budgetCurrency ?? undefined)}`
      : null,
    exportTrip.pace ? `${formatPaceLabel(exportTrip.pace)} pace` : null
  ].filter((value): value is string => Boolean(value));
}

function formatTripSubtitle(exportTrip: ExportTrip): string {
  if (!exportTrip.startDate) {
    return "Itinerary summary";
  }

  const endDate = addDaysToDate(exportTrip.startDate, Math.max(exportTrip.days - 1, 0));
  if (Number.isNaN(endDate.getTime()) || exportTrip.days <= 1) {
    return formatReadableDate(exportTrip.startDate);
  }

  return `${formatReadableDate(exportTrip.startDate)} - ${formatReadableDateFromDate(endDate)}`;
}

function formatDayDate(startDate: string | null | undefined, dayNumber: number): string {
  if (!startDate) {
    return "";
  }

  const date = addDaysToDate(startDate, dayNumber - 1);
  if (Number.isNaN(date.getTime())) {
    return "";
  }

  return ` · ${formatReadableDateFromDate(date)}`;
}

function formatItemHeading(item: ItineraryItem): string {
  const parts = [
    item.time || "Untimed",
    item.name || "Itinerary item",
    item.type ? formatInterestLabel(item.type) : null
  ].filter(Boolean);

  return parts.join(" - ");
}

function appendWeatherSummary(lines: TripPdfLine[], weatherSummary?: ExportWeatherDay[] | null) {
  if (!weatherSummary?.length) {
    return;
  }

  lines.push({ text: "Weather summary", variant: "heading" });
  weatherSummary.forEach((day) => {
    const temps =
      day.temperatureMinC != null && day.temperatureMaxC != null
        ? `${formatNumber(day.temperatureMinC)}-${formatNumber(day.temperatureMaxC)} C`
        : null;
    const rain =
      day.precipitationChance != null ? `${formatNumber(day.precipitationChance)}% rain` : null;

    lines.push({
      text: [
        `Day ${day.dayNumber}`,
        day.date ? formatReadableDate(day.date) : null,
        day.summary,
        temps,
        rain
      ]
        .filter(Boolean)
        .join(" - "),
      variant: "body",
      indent: 14
    });
  });
}

function appendDistanceSummary(lines: TripPdfLine[], distanceSummary?: ExportDistanceDay[] | null) {
  if (!distanceSummary?.length) {
    return;
  }

  lines.push({ text: "Distance summary", variant: "heading" });
  distanceSummary.forEach((day) => {
    lines.push({
      text: [
        `Day ${day.dayNumber}`,
        day.distanceKm != null ? `${day.distanceKm.toFixed(1)} km` : null,
        day.walkingMinutes != null ? `${Math.round(day.walkingMinutes)} min walking` : null
      ]
        .filter(Boolean)
        .join(" - "),
      variant: "body",
      indent: 14
    });
  });
}

function formatReadableDate(value: string): string {
  const date = addDaysToDate(value, 0);
  return Number.isNaN(date.getTime()) ? value : formatReadableDateFromDate(date);
}

function formatReadableDateFromDate(date: Date): string {
  const value = formatIcsDateTimeLocal(date, 0, 0).slice(0, 8);
  const normalized = `${value.slice(0, 4)}-${value.slice(4, 6)}-${value.slice(6, 8)}T00:00:00Z`;
  return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeZone: "UTC" }).format(
    new Date(normalized)
  );
}

function formatNumber(value: number): string {
  return Number.isInteger(value) ? String(value) : value.toFixed(1);
}
