"use client";

import type { AppNotification } from "@/entities/notification/model";
import { formatRelativeTime } from "@/lib/notifications/relative-time";
import { cn } from "@/shared/lib/cn";

export function NotificationGroupCard({ title, items, onSelect, onMarkTripRead, onMuteTrip, onMuteCategory }: { title: string; items: AppNotification[]; onSelect: (item: AppNotification)=>void; onMarkTripRead?: (tripId:string)=>void; onMuteTrip?: (tripId:string)=>void; onMuteCategory?: (tripId:string,category:string)=>void }) {
  const unread=items.filter((item)=>!item.readAt).length;
  const tripId=items[0]?.tripId; const category=items[0]?.category;
  return <section className="overflow-hidden rounded-[18px] border border-sand-300 bg-white"><header className="flex items-center justify-between gap-3 bg-sand-50 px-4 py-3"><div><h3 className="text-[13.5px] font-semibold text-cocoa-900">{title}</h3><p className="text-[11.5px] text-cocoa-400">{items.length} update{items.length===1?"":"s"}</p></div><div className="flex flex-wrap items-center justify-end gap-2">{unread&&tripId&&onMarkTripRead?<button type="button" className="text-[10.5px] font-semibold text-cocoa-500 underline" onClick={()=>onMarkTripRead(tripId)}>Mark trip read</button>:null}{tripId&&onMuteCategory?<button type="button" className="text-[10.5px] font-semibold text-cocoa-500 underline" onClick={()=>onMuteCategory(tripId,category)}>Mute category</button>:null}{tripId&&onMuteTrip?<button type="button" className="text-[10.5px] font-semibold text-cocoa-500 underline" onClick={()=>onMuteTrip(tripId)}>Mute trip</button>:null}{unread?<span className="rounded-full bg-clay-tint px-2 py-1 text-[11px] font-semibold text-clay-deep">{unread} unread</span>:null}</div></header>
    <ul>{items.map((item,index)=><li key={item.id} className={index?"border-t border-sand-200":""}><button type="button" onClick={()=>onSelect(item)} className={cn("w-full px-4 py-3 text-left transition hover:bg-sand-50",!item.readAt&&"bg-sand-100/70")}><span className="flex items-center gap-2"><span className="text-[13.5px] font-semibold text-cocoa-900">{item.title}</span>{item.groupedCount>1?<span className="rounded-full bg-sand-200 px-2 py-0.5 text-[10px] font-semibold text-cocoa-500">×{item.groupedCount}</span>:null}<span className={cn("rounded-full px-2 py-0.5 text-[10px] font-semibold",item.priority==="urgent"?"bg-[#FBE7E2] text-[#9D3324]":item.priority==="high"?"bg-[#FDF0D7] text-[#835D19]":"bg-sand-200 text-cocoa-500")}>{item.priority}</span></span><span className="mt-1 block text-[12.5px] leading-relaxed text-cocoa-500">{item.message}</span><span className="mt-1.5 block text-[11px] text-cocoa-400">{item.category.replaceAll("_"," ")} · {formatRelativeTime(item.latestEventAt||item.createdAt)}</span></button></li>)}</ul>
  </section>;
}
