"use client";

import { useTranslations } from "next-intl";
import type { TripRecapContent } from "@/types/recap";

function List({ items, empty }: { items: string[]; empty: string }) { return items.length ? <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-cocoa-700">{items.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul> : <p className="mt-2 text-sm text-cocoa-500">{empty}</p>; }
function money(value?: { amount: number; currency: string }) { return value ? new Intl.NumberFormat(undefined, { style: "currency", currency: value.currency }).format(value.amount) : "—"; }

export function RecapSections({ recap }: { recap: TripRecapContent }) {
  const t = useTranslations("recap");
  const planned = recap.plannedVsActual;
  return <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-3xl border border-sand-300 bg-white p-5"><h2 className="font-newsreader text-2xl text-cocoa-900">{t("plannedActual")}</h2><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-cocoa-500">{t("planned")}</dt><dd className="font-semibold">{planned.plannedItemCount}</dd></div><div><dt className="text-cocoa-500">{t("completed")}</dt><dd className="font-semibold">{planned.doneItemCount}</dd></div><div><dt className="text-cocoa-500">{t("skipped")}</dt><dd className="font-semibold">{planned.skippedItemCount}</dd></div><div><dt className="text-cocoa-500">{t("delayed")}</dt><dd className="font-semibold">{planned.delayedItemCount}</dd></div></dl><p className="mt-3 text-sm text-cocoa-700">{t("completion", { value: Math.round(planned.completionRate * 100) })}</p><List empty={t("none")} items={[...planned.skippedItems, ...planned.delayedItems]}/></section><section className="rounded-3xl border border-sand-300 bg-white p-5"><h2 className="font-newsreader text-2xl text-cocoa-900">{t("budget")}</h2><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-cocoa-500">{t("planned")}</dt><dd className="font-semibold">{money(recap.budget.plannedTotal)}</dd></div><div><dt className="text-cocoa-500">{t("actual")}</dt><dd className="font-semibold">{money(recap.budget.actualTotal)}</dd></div><div><dt className="text-cocoa-500">{t("variance")}</dt><dd className="font-semibold">{money(recap.budget.varianceAmount)}</dd></div><div><dt className="text-cocoa-500">{t("receipts")}</dt><dd className="font-semibold">{recap.budget.receiptCoveragePercent}%</dd></div></dl><List empty={t("none")} items={recap.budget.topCategories.map((category) => `${category.category}: ${money(category.total)}`)}/></section><section className="rounded-3xl border border-sand-300 bg-white p-5"><h2 className="font-newsreader text-2xl text-cocoa-900">{t("route")}</h2><p className="mt-2 text-sm text-cocoa-700">{recap.routeAndTransport.summary || t("none")}</p><List empty={t("none")} items={recap.routeAndTransport.issues}/></section><section className="rounded-3xl border border-sand-300 bg-white p-5"><h2 className="font-newsreader text-2xl text-cocoa-900">{t("verification")}</h2><p className="mt-2 text-sm text-cocoa-700">{recap.verification.summary || t("none")}</p><List empty={t("none")} items={recap.verification.issues}/></section><section className="rounded-3xl border border-sand-300 bg-white p-5 lg:col-span-2"><h2 className="font-newsreader text-2xl text-cocoa-900">{t("lessons")}</h2><List empty={t("none")} items={recap.lessonsLearned}/><p className="mt-4 text-sm text-cocoa-600">{t("checklistProgress", { completed: recap.checklistAndReminders.completedChecklistItems, total: recap.checklistAndReminders.totalChecklistItems, reminders: recap.checklistAndReminders.completedReminders, remindersTotal: recap.checklistAndReminders.totalReminders })}</p></section></div>;
}
